AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gets stock prices.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/stockprices
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /getPrices
            Method: get