// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "org.alex859/stockprices/domain/entity"
import mock "github.com/stretchr/testify/mock"

// CurrentPriceProvider is an autogenerated mock type for the CurrentPriceProvider type
type CurrentPriceProvider struct {
	mock.Mock
}

// GetCurrentPrice provides a mock function with given fields: ticker
func (_m *CurrentPriceProvider) GetCurrentPrice(ticker entity.Ticker) (entity.CurrentPrice, error) {
	ret := _m.Called(ticker)

	var r0 entity.CurrentPrice
	if rf, ok := ret.Get(0).(func(entity.Ticker) entity.CurrentPrice); ok {
		r0 = rf(ticker)
	} else {
		r0 = ret.Get(0).(entity.CurrentPrice)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Ticker) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
