// Code generated by mockery v1.0.0. DO NOT EDIT.

package googlefinance

import entity "org.alex859/stockprices/domain/entity"
import mock "github.com/stretchr/testify/mock"

// MockResponseConverter is an autogenerated mock type for the ResponseConverter type
type MockResponseConverter struct {
	mock.Mock
}

// ConvertToCurrentPrice provides a mock function with given fields: response
func (_m *MockResponseConverter) ConvertToCurrentPrice(response Response) (entity.CurrentPrice, error) {
	ret := _m.Called(response)

	var r0 entity.CurrentPrice
	if rf, ok := ret.Get(0).(func(Response) entity.CurrentPrice); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Get(0).(entity.CurrentPrice)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Response) error); ok {
		r1 = rf(response)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConvertToPriceHistory provides a mock function with given fields: response
func (_m *MockResponseConverter) ConvertToPriceHistory(response Response) (entity.PriceHistory, error) {
	ret := _m.Called(response)

	var r0 entity.PriceHistory
	if rf, ok := ret.Get(0).(func(Response) entity.PriceHistory); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Get(0).(entity.PriceHistory)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Response) error); ok {
		r1 = rf(response)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
